# Generated by Django 3.2.9 on 2022-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='image_market',
            new_name='image',
        ),
        migrations.AddField(
            model_name='market',
            name='location',
            field=models.JSONField(default=1, verbose_name="Location Jo'naitish"),
            preserve_default=False,
        ),
    ]
