# Generated by Django 3.2.9 on 2022-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('agency', '0002_auto_20220912_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='company_document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='full_name',
            new_name='owner_full_name',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='productgiven',
            name='product',
            field=models.ManyToManyField(related_name='product', to='product.Product'),
        ),
    ]
